import { rmSync, existsSync, writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { db, dbPath, closeDb, insert, q1, tx, run } from '../lib/db.ts';
import { ROOT } from '../lib/db.ts';
import { id } from '../lib/ids.ts';
import { nowIso, mkDate } from '../lib/dates.ts';
import { hashPassword } from '../lib/auth.ts';
import { Rng, GLOBAL_SEED } from '../lib/rng.ts';
import { ROLE_LABELS, type Role } from '../lib/rbac.ts';
import { setDials, DEFAULT_DIALS } from '../lib/sim/dials.ts';
import { seedPhases } from './parts.ts';

/** Deterministic demo seed (§8): Summit Ridge Management Co., three
 * properties, staff for every role, and (as phases land) 14 months of
 * operating + financial history generated through the REAL pipelines.
 * `npm run seed` is idempotent; `npm run seed -- --reset` rebuilds. */

const QUIET = process.argv.includes('--quiet');
const RESET = process.argv.includes('--reset');

export function log(msg: string): void {
  if (!QUIET) console.log(`  ${msg}`);
}

export interface SeedCtx {
  rng: Rng;
  orgId: string;
  businessDate: string;
  demoLogins: [string, string, string][]; // [persona, email, notes]
}

async function main(): Promise<void> {
  const t0 = Date.now();
  if (RESET || process.env.ORIEL_SEED_FRESH === '1') {
    closeDb();
    for (const suffix of ['', '-wal', '-shm']) {
      const p = dbPath() + suffix;
      if (existsSync(p)) rmSync(p, { force: true });
    }
    log('database reset');
  }
  db();

  if (q1('SELECT id FROM orgs LIMIT 1')) {
    console.log('Seed already present — run `npm run seed -- --reset` to rebuild.');
    return;
  }

  const rng = new Rng(GLOBAL_SEED);

  // Business date: 26th of the *fixed demo month* so a rent cycle, late-fee day
  // and month-end are all near (kept deterministic rather than wall-clock).
  const businessDate = process.env.ORIEL_SEED_DATE || mkDate(2026, 7, 26);

  const orgId = id('org');
  tx(() => {
    insert('orgs', {
      id: orgId,
      name: 'Summit Ridge Management Co.',
      slug: 'summit-ridge',
      business_date: businessDate,
      created_at: nowIso(),
    });
  });
  log(`org Summit Ridge Management Co. (business date ${businessDate})`);

  const seedCtx: SeedCtx = { rng, orgId, businessDate, demoLogins: [] };

  // platform admin + org staff personas
  const staff: [string, string, Role, string][] = [
    // [name, email-local, role, notes]
    ['Dana Whitfield', 'admin', 'ORG_ADMIN', 'full org access'],
    ['Marcus Bell', 'regional', 'REGIONAL_MANAGER', 'all properties'],
    ['Elena Ruiz', 'manager', 'PROPERTY_MANAGER', 'Summit Ridge + Cardinal Commons'],
    ['Jordan Pike', 'manager2', 'PROPERTY_MANAGER', 'The Foundry Lofts'],
    ['Tasha Nguyen', 'assistant', 'ASSISTANT_MANAGER', 'Summit Ridge'],
    ['Caleb Ford', 'agent', 'LEASING_AGENT', 'Summit Ridge'],
    ['Riley Chen', 'agent2', 'LEASING_AGENT', 'Foundry — Leasing Center'],
    ['Gus Romero', 'maintsup', 'MAINTENANCE_SUPERVISOR', 'all properties'],
    ['Sam Whitaker', 'tech', 'MAINTENANCE_TECH', 'Summit Ridge (demo cast)'],
    ['Lena Brooks', 'tech2', 'MAINTENANCE_TECH', 'Foundry Lofts'],
    ['Omar Silva', 'tech3', 'MAINTENANCE_TECH', 'floater — all properties'],
    ['Priya Raman', 'accountant', 'ACCOUNTANT', 'all properties (demo cast)'],
    ['Mia Okafor', 'marketing', 'MARKETING_MANAGER', 'all properties'],
  ];

  tx(() => {
    insert('users', {
      id: id('usr'), org_id: null, email: 'platform@oriel.demo', name: 'Oriel Platform Ops',
      kind: 'platform', password_hash: hashPassword('demo1234'), active: 1, created_at: nowIso(),
    });
    seedCtx.demoLogins.push(['Platform Admin', 'platform@oriel.demo', 'org onboarding']);
    for (const [name, local, role, notes] of staff) {
      const uid = id('usr');
      insert('users', {
        id: uid, org_id: orgId, email: `${local}@summitridge.demo`, name,
        kind: 'staff', password_hash: hashPassword('demo1234'), active: 1, created_at: nowIso(),
      });
      insert('role_assignments', {
        id: id('ra'), org_id: orgId, user_id: uid, role, scope_type: 'org', property_ids: '[]', created_at: nowIso(),
      });
      seedCtx.demoLogins.push([ROLE_LABELS[role], `${local}@summitridge.demo`, notes]);
    }
  });
  log(`${staff.length} staff users (password demo1234)`);

  setDials(orgId, DEFAULT_DIALS);

  // phase seeders (grow as phases land)
  await seedPhases(seedCtx);

  // demo logins doc
  const docsDir = join(ROOT, 'docs');
  mkdirSync(docsDir, { recursive: true });
  const table = seedCtx.demoLogins.map(([p, e, n]) => `| ${p} | \`${e}\` | \`demo1234\` | ${n} |`).join('\n');
  writeFileSync(
    join(docsDir, 'demo-logins.md'),
    `# Demo logins\n\nGenerated by \`npm run seed\`. Every account uses password \`demo1234\`.\n\n| Persona | Email | Password | Notes |\n|---|---|---|---|\n${table}\n`,
  );

  console.log(`Seed complete in ${((Date.now() - t0) / 1000).toFixed(1)}s — see docs/demo-logins.md`);
}

await main();
